language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: "AAvhTgQOskU8bCPE+AmtVwvAwT6Rz99nnqvcv1GmGUjh88MOMSCCcfGUf6mn7VcCbacTYo2J9u2qi5VeOrFPdWjtuuQ9+ODt2Q7p2Xqp/41MLu6ppBoP4Ox5mlsqhFJA1u3tPsKQEOyHIMcvnGc9TH8Th/hJp5jYSyCWiaD1Kpw="
    - secure: "GxZ1Ja3ffLG1+MmqcCKMggc6VQhrb4wjYdoO+DtTHvipbPQ4vNLDmOOyNIOJzVqOAqt68HuNpSA1b/41fDsddyEJ4VzuuPdpG77o5RUT2nE6b1coHHB3H2758zoNycQZP3LW5zi5as8NUkoh1p3yCe8CQcQ7ToSjW1KG2bE+r+M="

install:
   - npm install -g grunt-cli
   - npm -g install bower
   - npm install
   - bower install

notifications:
  email:
    on_failure : "change"

script:
   - grunt jshint test:remote

